### ISSUE TITLE
A better example?

### ISSUE THREAD

**Issue by guidedways** [Alkenso/sXPC#1]
This is brilliant, thank you! I wish though, the sample code used an easier to grasp example, such as the one Apple uses (fortune cookie request / response). Right now, the scary looking sample with process UIDs and `uid_t` doesn't help. It's confusing how one would go about using the framework. Maybe I'm just dumb?

**Comment by guidedways** [comment]
Also what's missing in the setup guide is how we need to still create the Obj-C compatible classes for each swift backed protocol.

**Comment by Alkenso** [comment]
Long story short...I've returned to active support of sXPC!

Issue fixed in 0.2.1 with better and simplified example. Please check and add more questions if have any
